In [303]:
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd

## Iterate over search pages

In [304]:
import re

def get_total_n_pages(url):

    r = requests.get(url)

    # Convert to beautiful soup object 
    webpage = bs(r.content)

    ulist = webpage.find("div", attrs={"class": "pagination"})
    # Set big one string to list of elements
    links = ulist.find_all("a")
    links

    actual_links = [link['data-search-nav-url-with-form'] for link in links]
    actual_links

    regexp = re.compile("page=(.*)$")

    ref_val = 0
    for id in range(0,len(actual_links)-1):

        curr_val = int( regexp.search( actual_links[id]).group(1) )
        if curr_val > ref_val:
            ref_val = curr_val

    return ref_val

## Main Data fetcher

In [305]:
# Load the webpage content 

def parse_html_content(url):
    r = requests.get(url)

    # Convert to beautiful soup object 
    soup = bs(r.content)

    # Print our 
    #print(soup.prettify() )
    
    '''
    for span in soup.findAll("table", class_ = "datatable"):#, id = "headline_avherald" ):
        #print( span.text )
    
    for span in soup.findAll("table", class_ = "datatable"):#, id = "headline_avherald" ):
        #print( span.text )
    '''
    table = soup.find( "table", {"class":"datatable"} )

    rows=list()
    for row in table.findAll("tr"):    

        row_parser = row.text.split('\n')
        row_output = [i for i in row_parser if i]
        #print( row_output  )

        rows.append( row_output)
    
    return rows

In [306]:
# Load parsed data into panda dataframe (table)
def load_data_into_df(list):
    df = pd.DataFrame( rows[1:], columns = rows[0])
    #df.head(5)
    
    return df

## Main function

In [311]:
url = "https://www.iata.org/en/about/members/airline-list/"

n_pages = get_total_n_pages(url)
#n_pages = 1
print( "Num.pages = ", n_pages)

my_df = pd.DataFrame()

for i in range(1, n_pages+1 ):
    rolling_url = "https://www.iata.org/en/about/members/airline-list/?page=" + str(i) + "&search=&ordering=Alphabetical"
    print(rolling_url)
    
    my_df = my_df.append( load_data_into_df(  parse_html_content(rolling_url) ) )

Num.pages =  30
https://www.iata.org/en/about/members/airline-list/?page=1&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=2&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=3&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=4&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=5&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=6&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=7&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=8&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=9&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=10&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=11&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=12&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=13&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=14&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=15&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=16&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=17&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=18&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=19&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=20&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=21&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=22&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=23&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=24&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=25&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=26&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=27&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=28&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=29&search=&ordering=Alphabetical
https://www.iata.org/en/about/members/airline-list/?page=30&search=&ordering=Alphabetical

In [314]:
my_df.tail()

,Airline Name,IATA Designator,3 digit code,ICAO code,Country / Territory
5,Aeromar,VW,942,TAO,Mexico
6,Aeromexico,AM,139,AMX,Mexico
7,Africa World Airlines,AW,394,AFW,Ghana
8,Air Algérie,AH,124,DAH,Algeria
9,Air Arabia,G9,514,ABY,United Arab Emirates

In [309]:
print("\n" * 100)